[tool.ruff]
# Same as Black.
line-length = 88
indent-width = 4

# Assume Python 3.12.
target-version = "py312"

[tool.ruff.lint]
# "E" (pycodestyle), "W" (pycodestyle), "F" (Pyflakes)
# "I" (isort), "C4" (flake8-comprehensions)
# "B" (flake8-bugbear)
select = ["E", "W", "F", "I", "C4", "B"]
ignore = []

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "lf"

[tool.mypy]
python_version = "3.12"
warn_return_any = true
warn_unused_configs = true
ignore_missing_imports = true
strict = true

# For pytest
[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "tests",
]
